Revert "bats fix"
This reverts commit d77cd64b8dbf91717cd2912217a3aa655967d950.

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -8,51 +8,50 @@ permissions:
 on:
   workflow_dispatch:
   schedule:
-    - cron: "0 0 1 * *"
+  # each first day of month
+  - cron: "0 0 1 * *"
   push:
   pull_request:
 
 jobs:
+
   build:
+
     runs-on: ubuntu-latest
+
     name: Install Bats and bats libs
     steps:
-      - uses: actions/checkout@v4
+    - uses: actions/checkout@v4
+    - name: Setup Bats and bats libs
+      id: setup-bats
+      uses: bats-core/bats-action@3.0.1
+    - name: entrypoint tests
+      shell: bash
+      env:
+       BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
+       TERM: xterm
+      run: bats tests/virtualavr-device/
 
-      - name: Setup Bats and bats libs
-        id: setup-bats
-        uses: bats-core/bats-action@3.0.1
-        with:
-          lib-path: ${{ runner.temp }}/bats-libs
-          install-path: ${{ runner.temp }}/bats
+    - name: Set up JDK 11
+      uses: actions/setup-java@v4
+      with:
+        java-version: 11
+        distribution: 'adopt'
+        cache: maven
+    - name: Set up Python
+      uses: actions/setup-python@v5
+      with:
+        python-version: '3.x'
 
-      - name: entrypoint tests
-        shell: bash
-        env:
-          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
-          PATH: ${{ steps.setup-bats.outputs.install-path }}/bin:${{ env.PATH }}
-          TERM: xterm
-        run: bats tests/virtualavr-device/
+    # Run your test script
+    - name: Run All Tests
+      run: ./run-tests.sh
 
-      - name: Set up JDK 11
-        uses: actions/setup-java@v4
-        with:
-          java-version: 11
-          distribution: 'adopt'
-          cache: maven
+    - name: Test Report
+      uses: dorny/test-reporter@v2
+      if: (success() || failure()) # run this step even if previous step failed
+      with:
+        name: Test report
+        path: demo/java/sketchtest/target/surefire-reports/*.xml,demo/python/*/test-results/pytest.xml,demo/python-gherkin/test-results/TESTS-*_behavior.xml
+        reporter: java-junit
 
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.x'
-
-      - name: Run All Tests
-        run: ./run-tests.sh
-
-      - name: Test Report
-        uses: dorny/test-reporter@v2
-        if: (success() || failure())
-        with:
-          name: Test report
-          path: demo/java/sketchtest/target/surefire-reports/*.xml,demo/python/*/test-results/pytest.xml,demo/python-gherkin/test-results/TESTS-*_behavior.xml
-          reporter: java-junit
